### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by mshick** [rollup/rollup-plugin-inject#1]
I could be wrong, but this plugin doesn't seem to work... Tests pass, and I've replicated them (for debugging) into my project's rollup config, and they always fail with `[Error: shorthand properties not yet implemented]`. If I go further, and set a `modules` property explicitly nothing is included, as though the plugin hadn't run. Very confusing. I thought it could be a problem with the version on npm, but have the same problems even if I clone and link the repo locally. 

I also don't see any dist files (which package.json points to) in the module pulled from npm.

**Comment by Rich-Harris** [comment]
Thanks – I forgot to add support for shorthand properties! (They need to be handled slightly differently to other types of reference.) And the failure to recognise `modules` was a dumb typo. Sorry, must have been half asleep.

I've just published 1.1.0 which should fix both issues – let me know if we need to reopen this.

**Comment by mshick** [comment]
Seems to be working now. Thanks!
