### ISSUE TITLE
External globals not being injected properly in 2.2.0

### ISSUE THREAD

**Issue by mxcoder** [rollup/rollup-plugin-inject#19]
Hi!
I have a project were we're using rollup plus some plugins and in our code we expect that window and document globals are injected into our IIFEs.

Rollup deps (according to yarn)
```
├─ karma-rollup-preprocessor@6.0.0
├─ rollup-plugin-babel@3.0.7
│  ├─ rollup-pluginutils@^1.5.0
│  └─ rollup-pluginutils@1.5.2
├─ rollup-plugin-commonjs@8.4.1
│  └─ rollup-pluginutils@^2.0.1
├─ rollup-plugin-import-alias@1.0.4
├─ rollup-plugin-inject@2.1.0
│  ├─ rollup-pluginutils@^2.0.1
├─ rollup-plugin-node-resolve@3.3.0
├─ rollup-plugin-uglify@4.0.0
├─ rollup-pluginutils@2.3.1
├─ rollup-stream@1.24.1
│  ├─ rollup@^0.49.2
│  └─ rollup@0.49.3
├─ rollup@0.63.5
```
In our code we don't directly import `window` or `document` but we do configure them as external in our rollup config:
```
{
  format: 'iife',
  sourcemap: false,
  external: ['window', 'document'],
  globals: {
    'window': 'window',
    'document': 'document'
  },
  plugins: [
    rollupPluginInject({
      modules: {
        win: 'window',
        doc: 'document'
      }
    })
  ]
}
```
So far this has been working pretty great, our entrypoint IIFE's receive `window` and `document` named as `win` and `doc`. And we can safely use `win` and `doc` in our modules.

But as soon as I updated to 2.2.0 this started to fail, and I got warnings about the plugin not being able to parse any of my entrypoints. Rolling back to 2.0.0 and even 2.1.0 fixes the issue.

Let me know if you would need more information.

**Comment by btd** [comment]
Do you have example entry? also what exact errro message says?

In 2.2.0 i updated plugin to use new rollup plugin system (so it will work only with more or less fresh rollup)

**Comment by btd** [comment]
Ping @mxcoder

**Comment by mxcoder** [comment]
Hey @btd , sorry I was preparing a sample case, which oddly, works as expected.
https://github.com/mxcoder/rollup-plugin-inject-issue-19

Although this is way simpler than my project setup. I'll try to reproduce it, but I guess we can close this as its not a problem in 2.2.0 alone, it must be something about my setup.

Apologies. And thanks for your time.

**Comment by btd** [comment]
Ok, feel free to reopen or open new, but with example that i can reproduce please.
