### ISSUE TITLE
Doesn't work with Windows

### ISSUE THREAD

**Issue by szwacz** [rollup/rollup-plugin-inject#2]
Hello,

This plugin doesn't work when run on Windows machine.

Let's say I want 'foo' to be injected. This plugin will generate then such line:
```
import { default as foo } form 'C:\full\path\to\foo.js';
```
The problem is that backslash isn't valid folder separator for node.js, so will be stripped to one long folder name: `Cfullpathtofoo.js`, which ofcourse must end with failure.

I'd have made an attempt to fix this myself, but this repo doesn't pass `npm install` on windows as well :)

**Comment by Rich-Harris** [comment]
@szwacz sorry for the long delay fixing this! Have just released 1.3.0 with Windows support, and enabled [Appveyor](https://ci.appveyor.com/project/Rich-Harris/rollup-plugin-inject) so it should stay fixed

**Comment by szwacz** [comment]
Thanks for doing this! :)
