### ISSUE TITLE
Can this be used to insert Boole as?

### ISSUE THREAD

**Issue by ncphillips** [rollup/rollup-plugin-inject#25]
I want to insert some booleans like `DEBUG` and `DEV`. Can this do that?

**Comment by btd** [comment]
I am worry no, you need plugin [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace).
This plugin has very simple purpose. If it founds usage of some symbol in code, it adds additional import from configuration, thus ponyfilling this symbol.

In you case it will be like:
```js
const replace = require('rollup-plugin-replace');

module.exports = {
....
replace({
DEV: JSON.stringify(true)
})
....
```

Something like this

**Comment by ncphillips** [comment]
Thank you so much! My google-foo has failed me
