### ISSUE TITLE
inject with commonjs

### ISSUE THREAD

**Issue by yrns** [rollup/rollup-plugin-inject#4]
Does this plugin work with the commonjs plugin? I'm trying to rollup [tape](https://github.com/substack/tape) and all my tests to run in a browser. I've verified that the injection of the process module in the output bundle, but it's not being linked up in the modules was injected for. The import statement is outside the __commonjs wrapper? My config is such:

```javascript
export default {
    entry: 'test.js',
    dest: 'test-bundle.js',
    plugins: [
        npm({jsnext: true, main: true, browser: true}),
        commonjs({include: 'node_modules/**'}),
        inject({include: 'node_modules/**',
                process: 'process',
                events: 'events',
                inherits: 'inherits'}),
        babel({exclude: 'node_modules/**'}),
    ],
    globals: {stream: '{}', path: '{}', fs: '{}'},
    format: 'iife',
    moduleName: 'test'
}
```

**Comment by Rich-Harris** [comment]
This was auto-closed with the merge of #5, but let me know if the issue persists
